### ISSUE TITLE
TEH

### ISSUE THREAD

**Issue by massar** [verisign/smaug#1]
README.md:
"The specific features supported are described in teh Release Notes"

TEH! :)

**Comment by glenwiley** [comment]
We are just trying to keep it hip ;)
--
Glen Wiley
Principal Engineer
Verisign, Inc.
(571) 230-7917

A5E5 E373 3C75 5B3E 2E24
6A0F DC65 2354 9946 C63A

**Comment by ginipginob** [comment]
Thanks for the catch.  Fixed teh issue. . . ;)
