### ISSUE TITLE
Ubuntu dependency wrong name gpgme-devel should be libgpgme11-dev

### ISSUE THREAD

**Issue by soulsymphonies** [verisign/smaug#6]
Hello, 

whilst installing the dependencies for smaug, I got stuck as there is no such package in the Ubuntu repositories, which is named gpgme-devel, so this command won't work:
sudo apt-get install gpgme-devel

After some research I found the the package is named differentely, it's called libgpgme11-dev, maybe you can update the manual so it includes the right package name, which would be
sudo apt-get install libgpgme11-dev

Would be nice, thank you ever so much,
Robert

**Comment by ginipginob** [comment]
Ah, thank you!  I will update it right now.
Eric
 

    On Friday, April 14, 2017 5:00 PM, Robert Christian <notifications@github.com> wrote:
 

 Hello,whilst installing the dependencies for smaug, I got stuck as there is no such package in the Ubuntu repositories, which is named gpgme-devel, so this command won't work:
sudo apt-get install gpgme-develAfter some research I found the the package is named differentely, it's called libgpgme11-dev, maybe you can update the manual so it includes the right package name, which would be
sudo apt-get install libgpgme11-devWould be nice, thank you ever so much,
Robert—

**Comment by soulsymphonies** [comment]
Thank you very much and also a huge thank you for this wonderful piece of software, great work!
I will close this issue now, as I've seen the manual is already updated.
Robert
